# -*- coding: utf-8 -*-
"""c_PA2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ylas4Uo9E53gepgogX1Vz4vuwWCkkudq
"""

from google.colab import drive
drive.mount('/content/drive')

import os
os.environ['PYTHONPATH'] += ":/content/drive/My Drive/Colab Notebooks/code/Detectron"
import sys
sys.path.insert(1,'/content/drive/My Drive/Colab Notebooks/code/Detectron')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My\ Drive/Colab\ Notebooks/dataset
# %cp *.tar.gz /content
# %cd /content

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !tar -xzvf Train.tar.gz
# !tar -xzvf Test_public.tar.gz
# !tar -xzvf Test_private.tar.gz

!echo "Finished tar unziping"
!ls
# %cd /content/drive/My Drive/Colab Notebooks/

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive/Colab Notebooks/
# %rm -rf  code
# %mkdir code
# %cd code
!git init
!git remote add origin https://github.com/kaarthik-raja/TDL_Pass2.git
!git pull origin master

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# %cd Detectron
# !make

!python tools/train_net.py \
    --cfg configs/12_2017_baselines/MR2.yaml \
    OUTPUT_DIR "/content/drive/My Drive/Colab Notebooks/models/fastrcnn2"

!python tools/test_net.py \
    --cfg configs/12_2017_baselines/retinanet_R-50-FPN_1x.yaml  \
    TEST.WEIGHTS '/content/drive/My Drive/Colab Notebooks/models/fastrcnn/train/coco_ass_train/retinanet/model_final.pkl' \
    NUM_GPUS 1

# !python tools/infer_simple.py --cfg configs/12_2017_baselines/retinanet_R-50-FPN_1x.yaml --output-dir ../../output \
#     --image-ext png --wts "/content/drive/My Drive/Colab Notebooks/models/fastrcnn/train/coco_ass_train/retinanet/model_final.pkl" ../../sample

